site_name: btractor
site_url: https://byron.github.io/btractor
site_description: "Build ALF job descriptions and serialize them for submission"

repo_url: https://github.com/Byron/btractor
dev_addr: 127.0.0.1:10002

docs_dir: ../../src/md
site_dir: ../../doc/mkdocs/html

pages:
- ['index.md', 'Home']
- ['license.md', 'License']

theme: yeti

copyright: Copyright &copy; 2014, <a href="https://www.linkedin.com/in/sebastianthiel">Sebastian Thiel & Contributors</a>.
